# fly.toml app configuration file generated for shy-shadow-3478 on 2023-06-19T19:43:32+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shy-shadow-3478"
primary_region = "nrt"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
